sonar.projectKey=flurryx
sonar.projectName=flurryx
sonar.projectVersion=0.8.3

sonar.sources=packages/core/src,packages/store/src,packages/rx/src,packages/flurryx/src,samples/taskflurry/src/app
sonar.tests=packages/core/src/__tests__,packages/store/src/__tests__,packages/rx/src/__tests__
sonar.test.inclusions=**/*.spec.ts

sonar.exclusions=**/node_modules/**,**/dist/**,**/__mocks__/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.host.url=http://localhost:9000
